### ISSUE TITLE
Docker-compose for M4 testnet

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE#10]
To demonstrate M3 we need a testnet of 3 substraTEE-node validators and a configurable number of workers (let's start with 2, each subscribed to a different validator)

Check out how hyperledger sawtooth uses docker-compose to bring up a local testnet with multiple validator nodes: 

https://sawtooth.hyperledger.org/docs/core/nightly/master/app_developers_guide/docker_test_network.html 

[docker-compose.yaml](https://sawtooth.hyperledger.org/docs/core/nightly/master/app_developers_guide/sawtooth-default-poet.yaml)

**Comment by electronix** [comment]
This will become relevant for M4 -> changing title

**Comment by electronix** [comment]
Done with M4 (aaa261931b6adc74930a611ced2ecac51ad37b7a).

Not using docker compose, but one docker image and tmux that launches 4 docker containers.
