### ISSUE TITLE
provisioning service for M3

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE#11]
In order to let more than one enclave operate on the state of a contract, the state encryption key needs to be known to all enclaves (and only to them)

Hyperledger Sawtooth solved this problem by partially trusting [provisioning services](https://github.com/hyperledger-labs/private-data-objects/tree/master/pservice)
These PS maintain secret shares for each contract and only provide these shares to registered enclaves.

Each contract defines a set of PS that provide secret shares (shamir) for their state encryption key

The enclave queries each PS to get *all* shares ( or M-of-N) and reconstructs the symmetric state encryption key.

**Comment by electronix** [comment]
Will probably become obsolete as the state encryption key will be distributed over a secure channel between the enclaves. The enclaves will trust each other by performing a mutual RA.

**Comment by brenzi** [comment]
agreed, but let's first wait for permission to modify milestones.
