### ISSUE TITLE
add Jenkinsfile for docker builds

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE#19]
we should keep track of all dockerfiles here

**Comment by electronix** [comment]
What do you want to do exactly? Build the docker images with Jenkins? Only building or also running the examples?

**Comment by brenzi** [comment]
I don't think we already have integration tests running where we really test the demo flow, right? If we can do it with reasonable effort, testing the M5 demo would be great.
The minimum should be a successful docker build.

**Comment by electronix** [comment]
Will not be implemented
