### ISSUE TITLE
Cross chain (bridge how to)

### ISSUE THREAD

**Issue by alanpoon** [scs/substraTEE#22]
I want to perform cross chain between 2 different substrate nodes. Am I supposed to modify https://github.com/scs/substraTEE-worker/blob/master/worker/src/main.rs to pipe the extrinsic transaction from 1 node to another node?

**Comment by brenzi** [comment]
Actually, we have a failed grant proposal for exactly this, possibly to be re-tried in a few months:
https://github.com/w3f/Web3-collaboration/pull/140

If you want to move on, have a look at the proposed approach. You actually might find our next planned additions useful, (a pending grant for implementing proof of inclusion) https://github.com/w3f/Web3-collaboration/pull/214
With a bit of luck, this might happen in Q1

Without this light-client functionality your bridge will trust the worker (not the enclave) which is very undesirable

**Comment by alanpoon** [comment]
With regards to w3f/Web3-collaboration#140,
Am I supposed to import the functionality of the [FinalityProofImport trait](https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/src/light_import.rs) into the enclave?

**Comment by brenzi** [comment]
As we haven't done this yet, I haven't looked into the details. I guess the [riot chat](https://riot.im/app/#/room/!HzySYSaIhtyWrwiwEV:matrix.org) is the better place for advice.

**Comment by brenzi** [comment]
I'll close this as no action seems required
