### ISSUE TITLE
substraTEE-signer on ARM TrustZone

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE#3]
write a simple wallet app for ARM that can sign and send transactions to substrate RPC.
Basic Idea described in:
https://github.com/scs/substraTEE-doc#substratee-signer

example code (javascript) using oo7: 
https://github.com/paritytech/oo7/issues/102

**Comment by electronix** [comment]
The substraTEE-signer does not exist anymore and therefore will not be implemented on ARM TrustZone in the near future.

**Comment by brenzi** [comment]
agreed. we should think about porting substraTEE-worker to ARM trustZone instead. Maybe @akoskinas can assess the difficulty of doing that with Trustonic SDK. I guess OP_TEE is out of question as we saw there are no integrity or confidentiality guarantees so far.
