### ISSUE TITLE
About Remote attestation, how could user know IAS Certificate on chain is actually from IAS Service ? 

### ISSUE THREAD

**Issue by bjwswang** [scs/substraTEE#33]
In the document,it mentioned 
```
Any user can now verify IAS signature and MRENCLAVE (given the substraTEE enclave can be built deterministically).
 See the example how you can extract MRENCLAVE after building the enclave
```
But if the service provider itself is malicious and put bad worker register info onto blockchain(In this case, the IAS Certificate could be faked but still verification on cert/signature is good), how could user identify this?

**Comment by brenzi** [comment]
If IAS is malicious we indeed have a problem. 

IF IAS acts correctly, there is no way how you could register a malicious worker enclave. the blockchain knows the root CA of IAS and can therefore verify the certificate which signs off the quote including the MRENCLAVE

**Comment by bjwswang** [comment]
@brenzi Thanks! that's the part missing in my mind. Attestion Verification report generated by IAS contains the IASReport Signing Certificate which could be verified as you mentioned. BTW... could you show me the cert verification code in blockchain ? 

Description in sgx-attestation-api-sepc
```
Report Signing Certificate Chain
The public part of Report Key is distributed in the form of an x.509 digital certificate called
Attestation Report Signing Certificate. It is a leaf certificate issued by the Attestation Report
Signing CA Certificate:
1) Attestation Report Signing CA Certificate: CN=Intel SGX Attestation Report Signing CA,
O=Intel Corporation, L=Santa Clara, ST=CA, C=US
2) Attestation Report Signing Certificate: CN=Intel SGX Attestation Report Signing, O=Intel
Corporation, L=Santa Clara, ST=CA, C=US
A PEM-encoded certificate chain consisting of Attestation Report Signing Certificate and
Attestation Report Signing CA Certificate is returned in a custom HTTP response header XIASReport-Signing-Certificate.
```

**Comment by bjwswang** [comment]
@brenzi I found the ROOT CA Cert in intel official website. https://api.portal.trustedservices.intel.com/EPID-attestation

**Comment by brenzi** [comment]
the code where we verify the certificate is here: 
https://github.com/scs/pallet-substratee-registry/blob/a8143a18a03abf5d546e3fd9d0042ececb448b30/ias-verify/src/lib.rs#L176

**Comment by bjwswang** [comment]
@brenzi awesome!
