### ISSUE TITLE
implement substraTEE-signer SGX demo

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE#4]
setup:
  * docker container running substraTEE-signer on Intel NUC Test machine `devsgx`, SGX in HW mode!
  * docker container running vanilla `substrate --dev` on Intel NUC Test machine `devsgx`. See [parity/substrate dockerhub](https://hub.docker.com/r/parity/substrate)

success scenario:
  * User *Hans* creates a new substrate account, in custody of substraTEE-signer enclave
  * substrate standard user *Alice* sends 1000 tokens to *Hans*' new account
  * *Hans* sends 100 tokens back to *Alice* by calling a `send` function in the substraTEE-signer enclave
  * account balances are correct

nice-to-have improvements:
  * password protection of substraTEE-signer `send` function 
  * OTP Password protection (GoogleAuthenticator, YubicoAuthenticator)

Hints:
  * check the following js code that performs the success scenario without SGX: https://github.com/paritytech/oo7/issues/102
  * https://polkadot.js.org/apps/#/explorer

**Comment by electronix** [comment]
This setup was rejected in favour of the proposed architecture containing the [substraTEE-worker](https://github.com/scs/substraTEE-worker) (see https://github.com/scs/substraTEE for the high-level architecture)
