### ISSUE TITLE
implement substraTEE-signer NOSGX demo

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE#6]
SAME as #4, but without using sgx. 

setup:
  * docker container running substraTEE-signer 
  * `substrate --dev` on Intel NUC Test machine `devsgx`. See [parity/substrate dockerhub](https://hub.docker.com/r/parity/substrate)

success scenario:
  * User *Hans* creates a new substrate account, in custody of substraTEE-signer 
  * substrate standard user *Alice* sends 1000 tokens to *Hans*' new account
  * *Hans* sends 100 tokens back to *Alice* by using substraTEE-signer
  * account balances are correct

Hints:
  * check the following js code that performs the success scenario: https://github.com/paritytech/oo7/issues/102
  * https://polkadot.js.org/apps/#/explorer

**Comment by brenzi** [comment]
Gavin is working on constructing and signing extrinsics: 
https://github.com/paritytech/substrate/pull/2109
not yet working

**Comment by brenzi** [comment]
Gavin's PR is working now. So is our first hardcoded client:
https://github.com/scs/substrate-client
sends a transfer form //Alice to //Bob using substrate's websocket interface

**Comment by electronix** [comment]
This setup was rejected in favour of the proposed architecture containing the [substraTEE-worker](https://github.com/scs/substraTEE-worker) (see https://github.com/scs/substraTEE for the high-level architecture)
