### ISSUE TITLE
Milestone 2: SubstraTEE PoC2: Running WASMI inside SGX enclave with simple STF

### ISSUE THREAD

**Issue by electronix** [scs/substraTEE#8]
Same as #2 with a running WASMI inside the Intel SGX enclave

WASMI: WebAssembly Interpreter (https://github.com/paritytech/wasmi)

**Comment by brenzi** [comment]
shouldn't this issue be an epic instead of a milestone?

**Comment by electronix** [comment]
thanks. corrected

**Comment by electronix** [comment]
Milestone 2 ready: https://github.com/scs/substraTEE/tree/M2
